---
- name: Install nginx
  hosts: all
  become: true
  tasks:
    - name: Install EPEL release package
      yum:
        name: epel-release
        state: present
      when: ansible_os_family == 'Redhat'
    
    - name: Update apache port from 80 to 8080
      lineinfile:
        path: /etc/httpd/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 8080
      when: ansible_os_family == "Redhat"

    - name: restart apache
      systemd:
        name: httpd
        state: restarted
      when: ansible_os_family == "Redhat"

    - name: Install nginx on CentOS 7
      yum:
        name: nginx
        state: present
      when: ansible_os_family == 'Redhat'

    - name: Nginx service restart
      service:
        name: nginx
        state: restarted
      when: ansible_os_family == 'Redhat'

    - name: Set SELinux to permissive mode
      selinux:
        policy: targeted
        state: permissive
      when: ansible_os_family == 'Redhat'

    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Nginx on Debian-based systems
      apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure Nginx service is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'





