---
- name: Install NGINX on CentOS 7 and configure to listen on port 8080
  hosts: server1
  become: true
  tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install NGINX package
      yum:
        name: nginx
        state: present

    - name: Update nginx port from 80 to 8080
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^Listen '
        insertafter: '^Listen '
        line: Listen 8080

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted

    - name: firewalld
      firewalld:
        port: 8080/tcp
        state: enabled
        permanant: true

    - name: firewalld restart
      systemd:
        name: firewalld
        state: restarted
  
