---
- name: Install and enable Apache HTTP Server (httpd) on CentOS 7
  hosts: server1
  become: true
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Enable and start httpd service
      service:
        name: httpd
        state: started
        enabled: yes

