---
- name: Install apache httpd on Centoes 7
  hosts: server1
  become: true
  tasks:
    - name: install apache package
      yum:
        name: httpd
        state: present

    - name: httpd service start
      systemd:
        name: httpd
        state: restarted

    - name: Update apache port from 80 to 8080
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^Listen '
        line: Listen 8080

    - name: restart apache port 8080
      systemd:
        name: httpd
        state: restarted

    - name: open firewalld port for apache
      firewalld:
        port: 8080/tcp
        state: enabled

    - name: start firewalld for apache service
      systemd:
        name: firewalld
        state: restarted
