---
- name: Install NGINX on CentOS 7 and configure to listen on port 8080
  hosts: server1
  become: true
  tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install NGINX package
      yum:
        name: nginx
        state: present

    - name: Stop NGINX service
      service:
        name: nginx
        state: stopped

    - name: Update NGINX configuration to listen on port 8080
      replace:
        path: /etc/nginx/nginx.conf
        regexp: 'listen\s+80;'
        replace: 'listen 8080;'
      notify: Restart NGINX

    - name: Start NGINX service
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

