---
- name: Uninstall Nginx
  hosts: all
  become: yes

  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped
      when: ansible_os_family == "Redhat"

    - name: Uninstall nginx
      yum:
        name: nginx
        state: absent
      when: ansible_os_family == "Redhat"

    - name: Stop Nginx service on Debian
      service:
        name: nginx
        state: stopped
      when: ansible_os_family == "Debian"

    - name: Remove nginx
      apt:
        name: nginx
        state: absent
      when: ansible_os_family == "Debian"
