---
- name: Uninstall Nginx
  hosts: server1
  become: yes
  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped

    - name: Uninstall nginx
      yum:
        name: nginx
        state: absent
     
